### ISSUE TITLE
Documentation clarification: custom ticket fields

### ISSUE THREAD

**Issue by russellhoff** [zendesk/zendesk_app_framework_sdk#35]
I've been several hours trying to fetch custom fields' data. Finally, I've made it possible.

According to your documentation, the way to accomplish such a task is:

| v1 | v2 |
| --- | --- |
| ticket.customField(fieldName) | client.get('ticket.customField:fieldName') |

That's not right. Working with CUSTOM ticket fields should be done replacing its fieldName by:

> "custom_field_" + customFieldId

If you've got a custom field whose ID is 26266575, you should do the following:
`var nombrePromise = client.get("ticket.customField:custom_field_26266575").then(function(data){
        console.log("Nombre: " + data);
        console.log(data);
    });
`

This task isn't well explained in the documentation, so I would ask you to clarify it.

Hope it helps.

**Comment by danielbreves** [comment]
Hi @russellhoff,

Apologies for the late reply and thanks for your feedback.

We've made some changes to the docs recently. I believe it's clearer now: https://developer.zendesk.com/apps/docs/apps-v2/support_api#ticket.customfieldfieldname

Will close the issue for now.

**Comment by russellhoff** [comment]
Thank you
