### ISSUE TITLE
client.invoke('preloadPane') not working in top_bar apps

### ISSUE THREAD

**Issue by MartijnSnels** [zendesk/zendesk_app_framework_sdk#40]
It seams the `client.invoke('preloadPane')` is not active in the framework making it impossible to preload data on the background for top_bar apps till the agent opens the top_bar app once.

**Comment by danielbreves** [comment]
Hi @MartijnSnels,

Apologies for the late reply. We weren't getting notified of issues being created here for some reason.

Is this still an issue for you? I just tested this and was able to successfully invoke `preloadPane` on a top bar app from a background location using the following code:

```js
var client = ZAFClient.init();

client.get('instances').then(function(instancesData) {
  var instances = instancesData.instances;
  for (var instanceGuid in instances) {
    if (instances[instanceGuid].location === 'top_bar') {
      client.instance(instanceGuid).invoke('preloadPane');
    }
  }
});
```

I'll close this issue for now, but please let us know if you're still having trouble.

**Comment by arthurmartinsdasilva** [comment]
Nice, thanks!!
