### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by cancan101** [zendesk/zendesk_app_framework_sdk#43]
Right now the only install option suggested is using a script tag. Would be ideal if this package were published to NPM.

**Comment by danielbreves** [comment]
Hi @cancan101,

Apologies for the late reply.

As the framework is in constant development, we'd like to have the ability to make internal breaking changes. This wouldn't work if we published it to NPM as developers would be able to run older incompatible patch versions. We may reconsider this in the future, but will close this issue for now.

**Comment by evenfrost** [comment]
@danielbreves @fvzzy would you mind to reconsider it now? Current GitHub version is 2.0.27, and npm one is 2.0.11, which is a bit outdated (more than a year actually).

**Comment by evenfrost** [comment]
Think you already know that but [np](https://github.com/sindresorhus/np) does a great job in assisting with publishing to npm.

**Comment by pacarvalho** [comment]
@danielbreves Can you please publish this to NPM? The library is updated every few months and having to maintain our own forks on NPM increases the chance of having legacy code that is more susceptible to breaking changes.

**Comment by danielbreves** [comment]
@pacarvalho @evenfrost I'm no longer part of the team maintaining this library, but I believe the only supported way of including ZAF SDK is still via the CDN: https://static.zdassets.com/zendesk_app_framework_sdk/2.0/zaf_sdk.min.js. See https://developer.zendesk.com/apps/docs/developer-guide/getting_started.
