### ISSUE TITLE
Wrong location in event

### ISSUE THREAD

**Issue by miedzinski** [zendesk/zendesk_app_framework_sdk#7]
Consider this:

    
    <script type="text/javascript" src="https://assets.zendesk.com/apps/sdk/latest/zaf_sdk.min.js"></script>

    <script>
        var app = window.ZAFClient.init();
        app.on('app.registered', function(ev) {
            console.log(ev.location);
        });
    </script>

    // app.js
    (function() {
        'use strict';

        return {
            events: {
                'app.registered': 'init'
            },

            init: function() {
                var location = this.currentLocation();
                console.log(location);
            }
        };

    }());

When I visit existing ticket in Zendesk, first `console.log` outputs `new_ticket_sidebar`, but the second `ticket_sidebar`. Of course the former is incorrect.

Same thing happens with:

    window.ZAFClient.init(function(c) {
        console.log(c.location); // new_ticket_sidebar, should be ticket_sidebar
    };

**Comment by danielbreves** [comment]
@miedzinski I can't repro this, is it still an issue?

**Comment by miedzinski** [comment]
I have just checked

```
window.ZAFClient.init(function(c) {
    console.log(c.location); // new_ticket_sidebar, should be ticket_sidebar
};
```

and it seems to behave correctly now. When creating new ticket, it's `new_ticket_sidebar`, when editing one, it's `ticket_sidebar`.

**Comment by danielbreves** [comment]
Ok, cool, closing for now.
